name: replido
description: An offline-first todo app using Replicant!

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  uuid: 2.0.1

  # To run the sample download the Replicant flutter sdk from:
  # https://s3-us-west-2.amazonaws.com/dev.roci.replicant/replicant-flutter-sdk.zip.
  # Then unzip it someplace, and insert that path here:
  replicant:
    path:
      /tmp/replicant-flutter-sdk/

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/bundle.js
